# Generated by Django 5.1.1 on 2024-09-23 14:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_dimension'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dimension',
            name='product',
        ),
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Characteristic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=255)),
                ('material_type', models.CharField(max_length=255)),
                ('dimension', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.dimension')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.product')),
            ],
        ),
    ]
