# Generated by Django 5.1.1 on 2024-09-23 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_remove_dimension_product_product_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dimension',
            old_name='weight',
            new_name='width',
        ),
        migrations.AlterField(
            model_name='characteristic',
            name='color',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='characteristic',
            name='material_type',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
